### ISSUE TITLE
Stesura verbale 2020_12_01

### ISSUE THREAD

**Issue by ToldoDM** [DPCMGroup/dpcm2077-docs#22]

**Comment by matteobudai** [comment]
VERIFICA(versione 0.0.2):
(pagina 3)->mettere tutto in minuscolo dopo elenco puntato(Ordine del giorno)
(pagina 4)->modificare tempo verbale(non ancora fatto)(Sono emersi alcuni dubbi che successivamente sono stati esposti ai vari referenti dei capitolati.)(riga 2-3  Sintesi dei progetti e valutazioni)
(pagina 4)->modificare professore in prof(riga 1 di Discussione template documenti vari)
(pagina 4)->modificare ogrganigramma(riga 1 di Organigramma e suddivisioni delle mansioni)
(pagina 4)->modificare canele(riga 1 di Canale comunicativo per lo sviluppo)
(pagina 4)->modificare professore in prof(riga 1 di Canale comunicativo per lo sviluppo)
(pagina 4)-> modificare(Si è lasciato in sospeso l’argomento, in quanto può
essere necessario che il referente del capitolato sia dentro tale canale.)

**Comment by matteobudai** [comment]
VERIFICA(versione 0.2.2):
Tutto corretto.
Si passa il contenuto a @samudg7 per l'approvazione.
