### ISSUE TITLE
Stesura verbale 2020_12_09

### ISSUE THREAD

**Issue by matteobudai** [DPCMGroup/dpcm2077-docs#23]

**Comment by samudg7** [comment]
VERIFICA(versione 0.0.1)
(pagina  3)->errore di battitura, generele al posto di generale
(pagina  4)->errore di battitura, espondendo al posto di esponendo
(pagina  4)->errore di battitura, fattibiltà al posto di fattibilità
(pagina 4)->errore di battitura, domandposte al posto di domande poste
(pagina 4)->Si è iniziato a discutere su come organizzare il glossario e a chi incaricare la stesura delle varie parole
trovate durante la stesura. al posto del precedente ->Si è iniziato a discutere su come organizzare il glossario e a chi incaricare la stesura delle varie parole.
(pagina 5)->stabilire un limite massimo per le riunioni e in supporto a questo potrebbe essere incaricata una persona di organizzare i tempi per evitare di oltrepassare il limite massimo. al posto del precedente ->stabilire un limite di tempo massimo per le riunioni e in supporto a questo potrebbe essere incaricata una persona che fa da moderatore.

**Comment by samudg7** [comment]
VERIFICA(versione 0.2.2):
Tutto corretto.
Si passa il contenuto a @ivan-piacere per l'approvazione.
