### ISSUE TITLE
Stesura verbale 2020_12_14

### ISSUE THREAD

**Issue by saraprivi** [DPCMGroup/dpcm2077-docs#24]

**Comment by ivanpak** [comment]
Verifica della versione 0.0.1.
Problemi riscontrati:
1. (Pagina 1) La data della prima stesura (2020-12-09) è precedente alla data della riunione.
2. (Pagina 3) Non sono indicati i nomi delle persone a cui sono affidati i documenti.
3. (Pagina 3) Leggendo non è chiaro che ognuno aggiunge le parole che trova al glossario.
Propongo "Si è deciso che ognuno contribuirà al glossario con i termini che utilizza durante la stesura della documentazione affidatagli"
4. (Pagina 5) Nel tracciamento delle decisioni mancano:
- Si è deciso di contattare Imola Informatica per conoscerne la reperibilità e i mezzi di comunicazione preferiti.
- Si è deciso che ogni componente aggiungerà al glossario le parole che incontra durante la stesura della documentazione di sua competenza.

**Comment by ivanpak** [comment]
(Versione 0.2.2.) Non ci sono problemi da sistemare. Affido il documento a @saraprivi per l'approvazione.
