### ISSUE TITLE
Stesura Studio di Fattibilità

### ISSUE THREAD

**Issue by samudg7** [DPCMGroup/dpcm2077-docs#26]

**Comment by ToldoDM** [comment]
- indicare riferimento a docuemnto esterno quando si parla di glossario nella sez 1.2 (glossario o glossario v1.0.0)
- nella sezione contro di blockCOVID, si fa riferimento ad un parere personale ("si spera"), che sia da togliere?
- nel capitolo 3 sezione I-II settimana si fa riferimento ad avvenimenti che non sono inerenti direttamente con il docmento (aka simil personali), che siano da togliere?
