### ISSUE TITLE
Stesura Verbale 2020_11_03

### ISSUE THREAD

**Issue by samudg7** [DPCMGroup/dpcm2077-docs#30]

**Comment by antobaddo** [comment]
@DanieleSpigolon

**Comment by antobaddo** [comment]
Verbale da verificare e approvare: @DanieleSpigolon verificatore @samudg7 approvatore

**Comment by DanieleSpigolon** [comment]
Documento verificato; non sono presenti errori; pronto per approvazione @samudg7
