### ISSUE TITLE
Stesura Verbale 2020_11_16

### ISSUE THREAD

**Issue by samudg7** [DPCMGroup/dpcm2077-docs#31]

**Comment by antobaddo** [comment]
Quando riuscite bisogna verificare e approvare il verbale del 16 novembre.
Verificatore:@saraprivi - Responsabile:@ivan-piacere

**Comment by antobaddo** [comment]
modifica di : DPCM 2077, inserimento dei report sui progetti degli anni precedenti, inserimento decisione git-flow
