### ISSUE TITLE
[VER] Stesura verbale 2020-12-18

### ISSUE THREAD

**Issue by DanieleSpigolon** [DPCMGroup/dpcm2077-docs#34]
Stesura verbale del 2020-20-18.

Redattore: @ivan-piacere 
Verificatore: @saraprivi 
Approvatore: @DanieleSpigolon 

Stendere il verbale basato sull'ordine del giorno:
- a
- b
- c

**Comment by antobaddo** [comment]
E’ apprezzabile -> È apprezzabile

**Comment by antobaddo** [comment]
- E’ apprezzabile -> È apprezzabile
- perchè -> perché (2 attestazioni)
- La discussione si è concentrata sui TEST da effettuare. visto che il testo è organizzato come domanda e risposta, devono essere chiare le aggiunte "spurie" meglio -> [La discussione si è concentrata quindi sui TEST da effettuare. (NdR)]
- Siamo liberi di gestire la problematica come preferiamo. (stesso discorso di sopra)-> Siete liberi di ... come preferite 
-  Una postazione può essere igienizzata anche da dipendenti diversi da chi l’ha utilizzata
l’ultima volta? -> rispetto a chi l'ha utilizzata
- ad una postazione eliminata -> a una postazione

**Comment by ivanpak** [comment]
affido il verbale a @saraprivi per la verifica
