### ISSUE TITLE
[VER] Stesura verbale 2020-12-21

### ISSUE THREAD

**Issue by antobaddo** [DPCMGroup/dpcm2077-docs#35]
Stesura verbale del 2020-12-21.

Redattore: @saraprivi 
Verificatore: @DanieleSpigolon 
Approvatore: @antobaddo 

Stendere il verbale basato sull'ordine del giorno:
- a
- b
- c

**Comment by DanieleSpigolon** [comment]
@saraprivi 
Verifica 0.1.1: Gantt al posto di Grantt.
GitHub al posto di github.
Aggiungere la decisione sul fatto che il gruppo non segue una struttura fissa per l'invio di email al committente / proponente.
E' richiesto però che le email vengano inviate dal responsabile avendo cura di includere il logo del gruppo.

**Comment by DanieleSpigolon** [comment]
Verifica 0.2.2: il verbale è pronto per l'approvazione; Sono stati anche sistemati gli accenti delle E.
@antobaddo
