### ISSUE TITLE
Verifica Introduzione e Processi Primari nelle Norme di Progetto

### ISSUE THREAD

**Issue by ivanpak** [DPCMGroup/dpcm2077-docs#39]

**Comment by antobaddo** [comment]
*FRONTESPIZIO*

- Titolo: basta BlockCovid
- Prof.~Tullio, Prof.~Riccardo
- Togliere descrizione
- nel piede: spaziare v 0.0.11

*REGISTRO MODIFICHE*
- Modifiche più recenti in alto
- Manca riga finale

*INTRODUZIONE*
- 1.1 
	- inserire rif. glossario a procedura e definirlo
	- inserire rif. glossario a "gruppo". 
	- ridondante (collaborare significa lavorare in comune). Meglio: Lo scopo [...] per assicurare al gruppo DPCM 2077 un modo di lavorare comune che garantisca quantificabilità, efficacia ed efficienza.
	- Nota: quantificabilità, efficacia ed efficienza le ho prese dalla definizione di processo.
	- In quest'ottica, questo documento dovrà essere visionato e accettato da tutti i componenti di DPCM 2007 a ogni sua approvazione. I membri di DPCM 2077 sono obbligati ad applicare ...
	- punto al posto di punto e virgola
- 1.2
	- lo scopo del prodotto è di ... evitare frasi lo scopo è quello di o simili
	- inserire rif. glossario a "applicazione"
	- a un server; a una stanza
	- tracciatura rif. glossario
	- postazione rif. a glossario
	- esaurimento delle postazioni non posti
	- garantire una tracciatura autenticata delle presenze e la registrazione di tutti i [...]

	- L'applicazione [...] 
		- tracciatura delle postazioni ... Usare tracciatura
		- pulizia (spiegare meglio ???)
		- generare uno storico [...]

	- elenchi puntati. Ultimo punto con punto anziché punto e virgola

	Server s minuscola. Manca punto dopo RFID.

-1.3 Specificare che la D pedice significa che si fa riferimento a un documento

-1.4 RIFERIMENTI
	- Standard ISO/IEC 12207:1995 è rif. informativo sennò è troppo prescrittivo. Togliere i ":" alla fine
	- verbale esterno: sostituire la descrizione estesa del documento con la sigla adatta e usando il comando di LaTeX opportuno. la  data è 2020 non 20


IMP. : Manca una spiegazione in cui si dica perché il documento è organizzato in processi primari, di supporto, organizzativi (rif. standard 12207) e cosa si intenda per essi.

*PROCESSI PRIMARI*

2.1.1 definire nel glossario progetto e processo e marcarli con glock

- solo prima attestazione dei termini da inserire nel glossario (es. proponente)
- manutenzione no manuntenzione
- mantenere lo stesso soggetto il fornitore e non lasciare la frase in modo impersonale (è inoltre necessario... si passa dunque)
- non so se sia corretto parlare di fasi (fasi sottintendono attività sequenziali... mentre noi miriamo all'incrementalità).

2.1.2 + che sul lavoro svolto è sul lavoro in itinere (il dialogo retrospettivo (ma è un discorso valido anche per altre attività) al termine dell'attività si fa ma non è una BEST PRACTICE; meglio avere un dialogo durante le attività in corso d'opera visto che aiuta a dare indicazioni correttive, quando siamo ancora in tempo utile per correggere)

- Tale rapporto permette di arrivare ad una collaborazione per quanto riguarda . NON CHIARO
- ad una -> a una
- accordarsi non acordarsi

2.1.3 [...]a cui i membri ...
- fasi. stesso discorso di prima

2.1.4.1
- redatto dall'Analista (mi riferirei ai ruoli in modo univoco)
- per la definizione dello studio di fattibilità si potrebbe mettere quello che ho scritto nello studio di fattibilità (introduzione e premessa all'analisi) ? prova a dare un occhio
- il gruppo non in gruppo. Punto finale elenco puntato

2.1.4.2 sviluppo s minuscola
- si parla di fasi 
- i ruoli non li metterei nel glossario

2.1.4.3
- vengono identificati dei processi degli standard. Non ho capito
- elenco puntato iniziale minuscola

2.23 iso... è rif. a documentazione

Non chiaro quando usi corsivo e quando no

2.2.4.1
- Analisi dei requisiti, il cui scopo è elencare e definire
- proggettisti con una g
- tracciamento di riferimenti sulla mole di lavoro per poter eseguire una stima dei costi. SPIEGARE MEGLIO
- ossia al posto di ovvero (può essere equivocato)

UML
linguaggio non lingiaggio.

2.2.4.3 Codifica
-programmazione e implementazione
- fasi di programmazione ed implementazione.

- membro non memnro
-indentazione non identazione
- costanti no costati
- lettere minuscole iniziale elenchi puntati
- ad una -> a una

**Comment by ToldoDM** [comment]
ho tenuto la dicitura "fasi", dato che nel documento suddivido gli argomenti per fasi, il che non significa che non siano incrementali.
Non ho ben capito la cosa dello studio di fattibilità: ho già scritto cosa contiente e non ho trovato nuove sezioni da specificare.
Il corsivo lo uso quando mi riferisco al gruppo, ai professori o al nome della documentazione (cioè senza fare riferimento ad una versione) e quello che hai segnato tu era effettivamente un riferimento ad una attività più che al documento.
Il tracciamento della mole di lavoro per stimare i costi sarà spiegato nello specifico nel documento analisi dei requisiti, devo solo accennare a cosa sarà presente.
Le lettere minuscole negli elenchi puntati dovrebbero essere messi solo se sono elementi singoli o fine a se stessi.

**Comment by antobaddo** [comment]
FRONTESPIZIO

- Togliere descrizione
- nel piede: inserire punto v. 0.0.11

1.2

- Cambiare "Il documento si compone di 3 processi fondamentali secondo ISO/IEC 12207:1995:" in "La struttura del documento si ispira alla suddivisione dei processi in tre tipologie desunta dallo standard ISO/IEC 12207:1995:"

- G pedice processi
- D pedice ISO/IEC 12207:1995

- Non tutti i processi di ISO 12207 sono stati affrontati nelle nostre norme. Mettere un asterisco vicino a quelli che sono stati oggetto di attenzione nel nostro documento o trovare un sistema più elegante per farlo.  (ES. Primari: acquisizione (NO), fornitura(SI), sviluppo(SI), gestione(NO) operativa e manutenzione(NO))

1.3
- lo scopo del prodotto è di [...] non lo scopo del prodotto è quello di
- mettere "." al posto di ";" dopo postazione"
- pulizia di una postazione; Per pulizia si intende segnare come igienizzata una postazione; -> pulizia di una postazione (ossia segnare igienizzata una postazione);
- generare uno storico

PROCESSI PRIMARI

Per fase si intende:
"La durata temporale entro uno stato del ciclo di vita o in una transizione tra essi (pensa agli automi), durante la quale si svolgono specifiche e univoche attività. Per tale motivo mal si adatta allo sviluppo incrementale che presenta la ripetizione di alcune attività."
Quindi per evitare ambiguità nel linguaggio è meglio usare un altro termine.

Studio di fattibilità: intendevo dire che ho dato una definizione dei contenuti del documento anche là. Ma teniamo pure come hai fatto tu.

Il corsivo è meglio toglierlo perché ci toccherebbe poi uniformare tutta la documentazione

Per l'elenco puntato ok... ho aggiornato le norme tipografiche sul drive (dacci comunque un occhio)

2.1.1
- Il processo di fornitura è composto dalle seguenti attività [ISO 12207 parla di attività]
- Ogni membro è tenuto ad attenersi a quanto esposto per tutte le fasi di progettazione, sviluppo e consegna del prodotto. -> Ogni membro è tenuto ad attenersi a quanto esposto durante la progettazione, lo sviluppo e la consegna del prodotto.


2.1.3
- a cui membri -> a cui i membri


2.1.4.1
- redatto dall'Analista .... togliere spazio fra l' A
- Conclusioni. "." al posto di ";"

2.1.4.2
Pianificazione: vengono pianificate le attività da eseguire nelle diverse fasi del progetto con rispettive scadenze; -> Pianificazione: vengono pianificate le attività da eseguire durante il progetto e le rispettive scadenze;

2.2.4.1
- delle Analisi dei Requisiti -> dell'Analisi
- Il tracciamento della mole di lavoro ... intendo dire che la frase non è cosi chiara, non che tu debba spiegare nel dettaglio. Cosa si intende per riferimenti? non si capisce. Mole di lavoro la eviterei come espressione

2.2.4.2
Si divide nelle seguenti fasi -> Si divide in:

2.2.4.3
- queste norme durante le fasi di programmazione ed implementazione. -> queste norme durante la programmazione e l'implementazione.

- agevolare le fasi di manutenzione -> agevolare la manutenzione
