### ISSUE TITLE
Verifica Processi di Supporto nelle Norme di Progetto

### ISSUE THREAD

**Issue by ivanpak** [DPCMGroup/dpcm2077-docs#40]

**Comment by antobaddo** [comment]
*PROCESSI DI SUPPORTO*

3.1.1 
- che riguardano la stesura dei documenti e l’approvazione di questi ultimi -> che riguardano la stesura e l'approvazione dei documenti.
- della REPOSITORY: (mettere ":")
- togliere il punto dopo il link

3.1.2
per la stesura -> (non è solo stesura ma anche verifica e approvazione) forse meglio generazione della documentazione (?)

3.1.3
sezione non capitolo

mi pare che scopo, aspettative e descrizione differiscano poco per contenuto. Che sia il caso di fare una cosa unica(?) uniformando il tutto ovviamente con le altre sezioni (?) DA VALUTARE

3.1.4.1
- cosa sono le regole accordate? 
- non è avanzata ma avanzamento del documento
- la nostra prassi prevede che il responsabile intervenga solo per "ordinare" la stesura di un documento, assegnare i ruoli (stesura e verifica) e approvare il documento. Non è coinvolto tra un passaggio e l'altro (es. stesura<->verifica). Quando il documento è stato redatto, il redattore avvisa il verificatore, se il doc verificato deve essere risistemato il verificatore avvisa il redattore e se la verifica va bene il verificatore avvisa il responsabile che a sua volta può approvare il documento se va bene o rigettarlo (il responsabile non fa da intermediario... Da ragionare alla prox riunione PRO: non c'è tempo perso nei passaggi di consegne CONTRO: non è approccio incrementale perché bisogna ri iniziare tutto da capo). correggere

- verificati ed approvati; -> verificati e approvati;
- togliere lo spazio prima dei ":" sui documenti
- mostrando no mostrano ; mostrando quello che per DPCM 2077, togliere virgola dopo interessanti
- e il proponente (varie occorrenze)
- no virgola prima di e "deve offrire, e quindi [...]"
- hanno lo scopo di riassumere in modo conciso i contenuti delle riunioni e soprattutto le decisioni prese da DPCM 2077.

- logo ed il nome -> e il 
- stato: aggiungere "verificato"

- togliere occupa la seconda pagina ... (se lunga può occupare più pagine)
- redazione per redatori
- verifica per verificatori

Indice
[...] registro delle modifiche. (mettere . al posto di ;

- [...] riguarda il Verbale - V questo può essere sia interno sia esterno.

Versionamento
- ad ogni -> a ogni
- l'azzeramento di y e zavviene solo quando x si incrementa

- tra i membri del team... i membri di DPCM 2077

3.5.1
che il prodotto soddisfi

3.5.2
la conformità del prodotto finito. (punto)

**Comment by antobaddo** [comment]
@ToldoDM @saraprivi 

- Sul registro delle modifiche indicare con precisione le modifiche (es. non un generico sistemati paragrafi / inserito paragrafo ma scrivere il numero della sezione / paragrafo coinvolto)

- Damiano credo tu abbia modificato 3.4 e non 3.5, esatto? se sì bisogna correggere nel registro delle modifiche


3.1.4.1

- verifica: [...] Terminato il controllo [...] prima fase, con le indicazioni delle parti da emendare.
- approvazione: è l’ultima fase del ciclo di vita del documento. In questa fase il responsabile autorizza o meno il rilascio il documento.

- aggiungere alla fine del ciclo di vita, dopo l'elenco puntato. "Il responsabile ha facoltà di intervenire, in ogni momento del ciclo di vita del documento, dando indicazioni se interpellato o per sua volontà."

Nota: 

- verificati ed approvati -> verificati e approvati. [e eufonica... vedi norme tipografiche su drive]
- Verbali : -> Verbali:

- stato: togliere "verificato" :( sorry (ultima decisione della riunione)

3.2.2.1
- viene incrementato dal verificatore ad ogni verifica; -> a ogni 

3.2.2.3
- suddivisi tra esterni ed interni: -> suddivisi tra esterni e interni

3.4 - 3.5


3.4.4.2
- Lo scopo dei test è di dimostrare -> Lo scopo dei test è dimostrare
- istruzioni aggiuntive: 
	* sucome -> su come 
	* interpreare -> interpretare
- un unità -> un'unità
- estensionelogica -> estensione logica
- "Svolti con l’aggregazione in un unico componente di due o più unità già testate, la loro ideologia di base sta nell’eseguire tali test in modo da combinare progressivamente più parti, espandendo via via il processo al test di moduli di un gruppo con quelli di altri gruppi." FRASE INVOLUTA 
 -> Vengono svolti aggregando due o più unità già testate in un unico componente ed espandendo, di fatto, i test di moduli di un gruppo con quelli di altri gruppi.

 - test di sistema: "Questo tipo di test porta alla luce le ipotesi errate che i diversi sviluppatori fanno su parti del software sviluppate da altri." intendi: avevano fatto (?) non capisco.

 3.4.5
 [...] negli editor Texmaker e TexStudio.
