### ISSUE TITLE
Verifica Processi Organizzativi nelle Norme di Progetto

### ISSUE THREAD

**Issue by ivanpak** [DPCMGroup/dpcm2077-docs#41]

**Comment by antobaddo** [comment]
*PROCESSI ORGANIZZATIVI*

4.1.1
- sostituire É con È (varie attestazioni)
- È stato creato un gruppo contenente i 7 membri del team di sviluppo -> È stato creato un gruppo contenente i 7 membri di DPCM 2077
- dopo il ":" nell'elenco puntato mettere minuscola
- ultimo punto dell'elenco puntato deve finire col punto
- sostituire epidemia con pandemia

- meglio evitare la parola team di sviluppo (visto che DPCM 2077 non è solo questo). Usare DPCM 2007 che fra l'altro è più corto....

4.1.2
- iniziale dell'elenco puntato sempre minuscola. ultimo item con "." finale
- Prof.~Tullio Prof.~Vardanega (sennò LaTeX spazia troppo)
- perché committenti con la c maiuscola?

4.1.3 è un paragrafo di comunicazione esterna (non lo metterei come altra sottosezione). Oltre al logo del gruppo direi che il responsabile si deve firmare.

4.2
- Nelle nostre riunioni è il responsabile che convoca la riunione, stende l'odg, assegnando la giusta priorità ai vari punti da discutere e conduce / modera la discussione. Se qualcuno del gruppo vuole proporre un argomento contatta i responsabili prima della riunione, che lo inseriranno nell'odg e gli daranno la priorità corretta e lo spazio se c'è. Il segretario redige solo il verbale.
Fai menzione anche all'odg temporaneo (doc condiviso in cui i membri del gruppo possono vedere l'odg della riunione in anticipo)
Inoltre alla riunione si validano le decisioni prese in corso settimana con documento annesso. ("Si è deciso di creare un documento dove raccogliere le decisioni prese nel corso della settimana per
non perderne traccia. Esse saranno validate alla prima riunione utile.")
- occhio che hai scritto gruppo GRUPPO
- manca la sezione dei tracciamenti delle decisioni (che è la funzione principale dei verbali)
- nomenclatura dei verbali: specifica che v. 1.0.0 è esempio di versione

4.2.2 
- vedo che l'hai specificato dopo il ruolo del responsabile... fa che sia tutto coerente.
- solito discorso sugli elenchi puntati
- perché a volte usi la maiuscola e a volte no? serve fissare una norma
- specificare cosa intendi per richieste degli altri componenti del gruppo (richieste di odg? o cosa? non chiaro)
- perché Zomm, Meet, Telegram tutto maiuscolo? serve fissare una norma

4.2.3
a essa

4.3
- mancano i documenti che qualche ruolo deve redigere (amministratore, responsabile di progetto)
- tip: guarda quello che ha scritto Tullio nel sito
-

4.3.1
cosa sono le condizioni di completezza? non chiaro

4.3.3
• Gli Analisti sono pochi, non formano una categoria popolosa; lo toglierei

4.3.4 un forte -> togliere maiuscola a u

4.5.2 
- poichè -> poiché
- indentificato -> identificato

4.5.3
- rappresentazione UML; É -> è

**Comment by antobaddo** [comment]
@DanieleSpigolon buon 2021 :)

4.1.2
- continuo i processi e le strategie adottate; -> mettere "."

4.1.2.1 
- apporre la propria firma. senza digitale (perché quella è una firma certificata)

4.2
- che convoca la riunione con scadenza settimanale

- cambiare l'ultima frase con: "In Google drive è stato creato un o.d.g. temporaneo dove i componenti di DPCM 2077 possono vedere l’o.d.g. della riunione in anticipo. Inoltre è stato creato un documento dove raccogliere le decisioni prese nel corso della settimana, tra una riunione e la successiva, per non perderne traccia. Esse saranno validate alla prima riunione utile. È compito del responsabile tenere aggiornati l'odg temporaneo e il tracciamento delle decisioni settimanali."

4.2.1

- riepilogo in in forma tabella -> riepilogo in forma tabellare

4.3.3
- applica soluzioni note ed ottimizzate -> e ottimizzate

CONSIGLIO: quando usi gli elenchi puntati in LaTeX non è necessario includere fra graffe il punto dell'elenco puntato. Non sta modificare niente del sorgente... è per le prossime volte che ti capiterà di usarlo. 
es. \item{punto dell'elenco puntato;} -> \item punto dell'elenco puntato;
le parentesi [ ] vanno usate invece in description. es. \item[tratto da descrivere:] descrizione ....;
