### ISSUE TITLE
[VER] Stesura verbale 2020-12-29

### ISSUE THREAD

**Issue by ToldoDM** [DPCMGroup/dpcm2077-docs#43]
Stesura verbale del 2020-12-29.

Redattore: @DanieleSpigolon 
Verificatore: @antobaddo 
Approvatore: @ToldoDM

**Comment by antobaddo** [comment]
CORREZIONI RICHIESTE
- manca "." dopo approvato
- ad inserire -> a inserire (2 attestazioni)
- le norme tipografiche / guide esistono già sul drive ma non sono state inserite. Scriverei che di inserire le esistenti norme tipografiche / guide in uso da DPCM 2077
- si è terrà ... togliere è
- mettere le virgolette sui titoli di BlockCOVID per evidenziarli meglio nella frase

- il termine della stesura è per il 2021 non 2020 (2 attestazioni)
- decisione 9.3 [...] di lasciare il branch master invariato
- decisione 9.10 (specificare che si parla del registro delle modifiche)

- CARTELLA CONTENITRICE: anche se la cartella rispecchia la denominazione del verbale, terrei solamente la data, che se ci tocca aggiornare qualcosa ogni volta bisogna cambiare il numero

bel lavoro
@DanieleSpigolon

**Comment by DanieleSpigolon** [comment]
@antobaddo verbale pronto per prossima verifica; poi approvazione
