### ISSUE TITLE
Verifica Piano di Progetto

### ISSUE THREAD

**Issue by antobaddo** [DPCMGroup/dpcm2077-docs#44]

**Comment by antobaddo** [comment]
*FRONTESPIZIO*

- titolo: solo BlockKCOVID
- destinatari:
	* Prof.~Tullio  Prof.~Riccardo (sennò vengono troppo spaziati)
	* solo DPCM 2077 (senza gruppo e spazio tra DPCM E 2077)
- sostituire redattori con Redazione
- sostituire verificatori con Verifica

- togliere descrizione


*REGISTRO MODIFICHE*
- ove possibile indicare precisamente il numero della sezione /paragrafo / etc... oltre al titolo

*PIÈ DI PAGINA*
- v. 0.0.12  (spaziare e aggiungere il punto)

*INTESTAZIONE*
Il mio .pdf è sfasato: logo fuori dalla banda grigia

*INTRODUZIONE*

SCOPO
- si scrive BlockCOVID (non blockCOVID o Block-Covid... varie attestazioni 1.1 - 1.2 -1.5)
- le parole da inserire nel glossario vanno indicate unicamente con \glock{} e non usando $ ... $ . Se vogliamo modificare il formato di glock{} lo facciamo nella configurazione.tex e in ogni nostro documento. Da parlarne alla prox riunione
- Covid-19
- sanificare da inserire nel glossario

DOCUMENTI
-Manca l'indicazione della D pedice per documenti. Da sistemare con gli altri documenti quando si uniforma scopo e documenti

RIFERIMENTI
- inserire D pedice Norme di Progetto
- Organigramma [...] L06...: mettere il link visibile.


*ANALISI DEI RISCHI*

- elenchi puntati:
	- mettere "." al posto di ";" nell'ultimo punto
	- attività e rischi con la lettera minuscola

Forse occorre specificare cos'è il piano di contingenza
- non riesco a inquadrare a cosa debba essere associata la tabella: analisi dei rischi / individuazione dei rischi? tutte e 2? Forse occorre spiegarlo con una premessa 

-tabella:
	- verrano asseganti -> verranno assegnati
	- compotenti -> competenti

	- si riscontri il problema , -> togliere lo spazio prima della virgola
	- più esperte su quella tecnologia
	- e in certi casi potrà posticipare le scadenze temporali
	- centrare la tabella; Occorrenza in linea con la definizione e lo stesso vale per Pericolosità

	- per rispettare le scadenze; in caso di forti mutamenti verrà comunicato tempestivamente al committente. -> aggiungere ";"
	- incarchi -> incarichi

	- R04 mi pare una ripetizione di quanto già detto sopra.. Non so se toglierlo, dammi una motivazione per tenerlo

	- in modo efficiente ed efficace.

	-RP3 può portare a incomprensioni chi? manca il soggetto

MODELLO DI SVILUPPO

- elenchi puntati:
	- mettere ";" al posto di "." eccetto l'ultimo punto in cui si mette "." al posto di ";" (vedere norme tipografiche sul drive)
- perché non perchè

**Comment by antobaddo** [comment]
REGISTRO MODIFICHE
Indicare precisamente il numero della sezione /paragrafo / etc... modificata/ creata oltre al titolo

1.1
Lo scopo del documento è quello di illustrare -> Lo scopo del documento è illustrare

1.5 SCADENZE
- Revisione di Accettazione con "." finale

2 Monitoraggio dei rischi con "." finale

SFASAMENTI NELLA TABELLA
- Occorrenza in linea con la definizione e lo stesso vale per Pericolosità. Se non ci sta usa delle sigle e una legenda nell'intestazione.
INTESTAZIONE
Grado di rischio
O (occorrenza)
P (pericolosità)
Livello: A(Alta) M(Media) B(Bassa)

Per es. Occorrenza Alta; pericolosità alta la sintettizi così: OA - PA

**Comment by ivanpak** [comment]
Sono stati corretti anche i costi del consuntivo

**Comment by ToldoDM** [comment]
### In generale gli elenchi puntanti hanno bisogno di punteggiatura nelle sezioni 4 6 7.

nella sezione 4.1.2.2:
- [..] individuare gli errori più comuni e, al contrario, -> toglierei al contrario.
- condivisone -> condivisione
- E' -> È

nella sezione 4.1.2.4:
- al posto di scrivere "3 periodi precedenti", scriverei 3 in lettere.

nella sezione 4.3.2.4:
- togliere il - prima di Codifica (primo punto).

nella sezione 5
- Figura2 -> Figura 2
- Amministartore -> Amministratore

**Comment by antobaddo** [comment]
Per identificare il grado di rischio sono stati usati i seguenti indici con rispettivi livelli di intensità:
• Pericolosità (P) - Alta (A), Media (M), Bassa (B);
• Occorrenza (O) - Alta (A), Media (M), Bassa (B).

E nella tabella metti per esempio:
PA - OA 

Spaziati altrimenti non si capisce.

Inserisci legenda dei diagrammi: barra verde sta per verifica, barra azzurra sta per..., barra nera sta per ...
