### ISSUE TITLE
[VER] Stesura verbale 2021-01-04

### ISSUE THREAD

**Issue by matteobudai** [DPCMGroup/dpcm2077-docs#45]

**Comment by matteobudai** [comment]
Stesura verbale del 2020-12-29.

Redattore: @antobaddo 
Verificatore: @ToldoDM 
Approvatore: @matteobudai

**Comment by ToldoDM** [comment]
nel tracciamento delle decisioni c'è una voce duplicata

**Comment by ToldoDM** [comment]
nel verbale esterno, segnerei metamask come voce glossario.

**Comment by ToldoDM** [comment]
Verifica ok. @matteobudai puoi approvare.
