### ISSUE TITLE
Verifica sezione 3 Casi d'uso Analisi Dei Requisiti

### ISSUE THREAD

**Issue by DanieleSpigolon** [DPCMGroup/dpcm2077-docs#47]

**Comment by DanieleSpigolon** [comment]
3.1.1
Si riferisce ad -> si riferisce a...
Amministratore scritto sbagliato

3.1.2
ad -> a

3.2
..ritenuto utile (inserire virgola)

3.2.1
postcondizione sostituire ad -> a 

3.2.5
disautentica -> disconnette
disautenticazione -> preme un pulsante per disconettersi e l'azione viene eseguita

3.2.6
iniziale elenco puntato minuscola. mettere ; nel primo punto dell'elenco
3.2.7
iniziale elenco puntato minuscola. mettere ; nel primo punto dell'elenco
3.2.8
iniziale elenco puntato minuscola. mettere ; nel primo punto dell'elenco
3.2.10
...e le vede -> e le visualizza
Mettere ; per ogni punto dell'elenco puntato tranne l'ultimo in cui si mette .
3.2.11
e lo può vedere -> visualizza

3.2.12
...codice inserito (inserire virgola) essa viene creata
Estensione: le -> se mettere punto alla fine

3.3

ed -> e
giù -> già
eliminare appunto

3.3.1 ad -> a

3.3.2
amministratore. (il punto è staccato)

iniziali minuscole elenco puntato, tutti i ; alla fine tranne nell'ultimo in cui ci va .

3.3.3
cancellazione minuscolo e punto alla fine

3.3.4
ad -> a
stesso discorso elenchi puntati sia in scenario che estensione

3.4
ed -> e
giù -> già
eliminare appunto

3.5
ed -> e
ad -> a
eliminare appunto

3.5.1
Estensioni: c minuscolo 

3.6

una postazione che non è più disponibile
se amministratore -> se l'amministratore

3.6.1

stesso discorso elenchi puntati (iniziali minuscole e tutti ; tranne che l'ultimo .)
3.6.2
od  -> oppure

3.6.4
ad -> a
stesso discorso elenchi puntati

3.6.5
stesso discorso elenchi puntati

dei dati e i dati già salvati nel sistema

3.6.7
nome e cognome minuscolo
3.6.8
nome e cognome minuscolo

codice della postazione ;
....l'utente occupava la postazione.

**Comment by DanieleSpigolon** [comment]
Verificato fino paragrafo 3.6.8

**Comment by DanieleSpigolon** [comment]
3.6.11 tagRFID staccato
Estensioni: lettera minuscola 
3.6.12
tagRFID staccato
3.6.13 telefono o smartphone? meglio smartphone 
3.6.15
tagRFID staccato
smartphone al posto di cellulare
Estensioni: discorso sugli elenchi puntati
3.6.16
tagRFID staccato
attivitato -> attivato
smartphone scritto sbagliato
3.6.17
smartphone scritto sbagliato
3.6.24
discorso sugli elenchi puntati
3.6.26 discorso elenchi puntati
3.6.27
scritto male effettuare
3.6.28
discorso sugli elenchi puntati
3.6.30
discorso elenchi puntati
3.6.31
schema delle postazioni (inserire virgola)
discorso elenco puntato, mettere minuscola e punto alla fine
3.6.32
...un messaggio di errore (inserire virgola)
discorso sugli elenchi puntati
....un messaggio di errore (inserire virgola)
3.6.35
discorso elenco puntato
3.6.36
...da un dipendente (inserire virgola)
igienizzare (inserire virgola)
...almeno un dipendente (inserire virgola)
3.6.37
elenco delle stanze
almeno un dipendente (inserire virgola) (due attestazioni)
3.6.38
almeno un dipendente (inserire virgola)
3.6.39 
[UC14.2] mettere virgola al posto di e
3.6.40
stanza, in seguito
3.6.41
stanza, in seguito

**Comment by ivanpak** [comment]
@DanieleSpigolon ho modificato gli UC6, UC6.1, UC6.2 e UC7 e aggiunto UC6.1.1, UC6.2.1, UC6.3, UC6.3.1, UC7.1, UC7.1.1 quindi bisognerebbe verificarli.

**Comment by DanieleSpigolon** [comment]
UC6 mettere punto dopo scenario principale
6.1.2 ore trascorse in ogni postazione
6.2.1 amministratore (inserire punto)
6.3 amministratore (inserire punto)
7.1 amministratore (inserire punto)
7.1.1 amministratore (inserire punto)
