### ISSUE TITLE
Verifica Piano di Qualifica

### ISSUE THREAD

**Issue by antobaddo** [DPCMGroup/dpcm2077-docs#48]

**Comment by antobaddo** [comment]
***INTRODUZIONE***

- Inserire come riferimento normativo le NdP e i verbali con Imola Informatica (verbale riunione esterna, verbali e-mail)

***QUALITÀ DI PROCESSO***

- Non mi è chiara la struttura della sezione. Forse conviene che specifichi come hai organizzato la trattazione nella premessa iniziale (ad esempio: 2.1.1 perché si parla delle metriche delle AdR (AdR è un processo di sviluppo?))
- Altro dubbio, che ti trasmetto: È lo standard che si è adattato alle nostre esigenze oppure i processi? 


2.1.3.1
- spiegare meglio cosa si intende per profondità di un sito (tipo numero di click necessari per arrivare all'informazione richiesta)

2.2.1.2
- non chiaro "Si tratta del valore del lavoro fatto fino al momento del
calcolo: denaro guadagnato fino a quel momento.""


***QUALITÀ DI PRODOTTO***
- affinchè -> affinché
- grazie a dei parametri che valutano il grado di raggiungimento di qualità
- per raggiungere gli obiettivi qualitativi

3.1.1
"." finale dell'elenco

- per fare riferimento ai documenti si usa il comando \dext{} 
- per inserire espressioni complesse non in linea (che sono di difficile lettura si usa: \[ espression \]
- il $ usalo quando fai riferimento per es. a una variabile in linea nel corso del testo $ variabile $
- ho modificato metodo di misura così puoi vedere cosa intendo

3.2.2.1
- modificare espressione e variabile

3.4.2.1
- modificare espressione e variabile
- Spostare quanto hai scritto nella sezione Qualità di processo e qui fare semplicemente riferimento alla sezione. Cosa intendi per licenza elementare? non chiaro

3.4.2.2
MEMO: Bisogna ricordarsi di integrare / emendare questa parte una volta che capiamo come funziona la libreria di Python

3.5.1
"." finale dell'elenco puntato

3.5.2.1
- cambiare espressione e variabile


***APPENDICE A***

A.1.1
La seguente osservazione la faccio non sapendo se altrove è già stata risolta:
- Forse è il caso di specificare cosa si intende per metrica, qualità in uso e qualità esterna? Magari nel glossario oppure è sufficiente definirlo in linea.

- Ed in uso -> e in uso

A.1.2
- NON CHIARO: dall’operatività e dall’osservazione durante la sua esecuzione

A.1.3
- ed in uso -> e in uso
- manca il "." dopo condizioni reali
- non chiaro cosa si intende per condizioni reali
- Il livello di qualità in uso è raggiunto quando sia stato
raggiunto sia il livello di qualità esterna sia il livello di qualità interna. -> Il livello di qualità in uso è raggiunto quando sia il livello di qualità esterna sia il livello di qualità interna sono stati raggiunti.
- ad ottenere -> a ottenere

A.1.4.1
- ed obiettivi -> e obiettivi
- prefissati all'utente? o dall'utente?
- ed operare -> e operare

A.1.4.2
- che si verifichino

A.1.4.4
- ad usare -> a usare
- operabilità: farne uso cosa? a cosa si fa riferimento... specificare
- ad un altro -> a un altro

**Comment by antobaddo** [comment]
PER TUTTI
Inserire il numero delle sezioni nel registro delle modifiche

QUALITÀ DI PROCESSO
- ribaltabile -> attribuibile

QUALITÀ DI PRODOTTO
- per raggiungere gli obiettivi qualitativi. Manca il "."

3.5.2.1
- Mettere "R =" sulla riga dell'equazione

**Comment by samudg7** [comment]
***Verifica Appendici §B, §C***

-B1: Si potrebbe aggiungere
Problema: incontro con il proponente, soluzione zoom, scrittura mail, gruppo telegram creato ad hoc con il proponente.

-B2: Si potrebbe aggiungere
Valutazioni sui ruoli, integrare altri ruoli (ad esempio il verificatore, analista e amministratore).

**Comment by matteobudai** [comment]
VERIFICA SEZIONE 4:
Si può specificare (anche per leggibilità) nel  4 o 4.1 cosa si intende per i valori assunti dallo stato e dal codice oltre al tipo di test. Ad esempio 2->desiderabile, F->funzionale;

4.1:
-Mettere ";" nell'elenco puntato tranne ultimo punto che va "."

4.2:
- TS2F1 -> per il login e per l'applicazione
- TS1F2.1 -> credenziali errate
- ripetuto 2 volte TS1F5.5
- TS1Q6-> nella sua interezza
- TS1Q7 -> maggiore o uguale dell'ottanta
- TS1V8 -> sia di almeno l'ottanta

**Comment by ToldoDM** [comment]
> VERIFICA SEZIONE 4:
> Si può specificare (anche per leggibilità) nel 4 o 4.1 cosa si intende per i valori assunti dallo stato e dal codice oltre al tipo di test. Ad esempio 2->desiderabile, F->funzionale;

ho letto che molte correzioni fatte da tullio criticava il fatto che queste cose riguardano le norme di progetto, infatti ho modificato le norme di progetto dei test per questo motivo.

**Comment by ToldoDM** [comment]
> _**Verifica Appendici §B, §C**_
> 
> -B1: Si potrebbe aggiungere
> Problema: incontro con il proponente, soluzione zoom, scrittura mail, gruppo telegram creato ad hoc con il proponente.
> 
> -B2: Si potrebbe aggiungere
> Valutazioni sui ruoli, integrare altri ruoli (ad esempio il verificatore, analista e amministratore).

- Per quanto riguarda il B1 diciamo che è già sommato nel problema dell'incontro, andrei a ripetere metà soluzioni già adottate per l'incontro del gruppo stesso. Poi in secondo luogo presumo che ci si incontrasse con il proponente comunque via comunicazioni telematiche e non di persona.
- Per quanto riguarda B2, si, si potrebbe aggiungere, però non ho idee chiare di cosa scrivere e alla fine non è obbligatorio scrivere le problematiche di ogni ruolo, ma bensì le problematiche più rilevanti. Se vuoi che scriva qualcosa di specifico, lo metto, sennò possiamo lasciare anche così.
