### ISSUE TITLE
Verifica Glossario

### ISSUE THREAD

**Issue by matteobudai** [DPCMGroup/dpcm2077-docs#51]
È richiesta la verifica del documento sopracitato da:
- @matteobudai 
- @ivan-piacere

**Comment by matteobudai** [comment]
Workflow -> per svolgere attività
Smart contract ->verificaredefinizione al singolare

**Comment by matteobudai** [comment]
Workflow -> per svolgere attività
Smart contract ->verificaredefinizione al singolare

**Comment by matteobudai** [comment]
Decidere se open source o open-source
Workflow -> per svolgere attività
Smart contract ->verificare la negoziazione
Smart contract ->definizione al singolare
Real-time -> con il termine
Pytorch -> ideata
Publish/Subscribe -> Similmente i subscriber possono
Processo ->che assicuri
Postazione ->appoggia il cellulare

@ToldoDM  @antobaddo

**Comment by matteobudai** [comment]
Bluetooth -> senza fili a distanza di poche decine di metri.
NFC-> una tecnologia di trasmissione di dati senza fili a distanze tipicamente
QR Code -> smartphone
Product baseline -> toglierei le 2 virgole

@ivan-piacere

**Comment by ivanpak** [comment]
* AWS Appsync
connessione sicura **a fonti di dati**
* AWS Gamelift
è un servizio che distribuisce, gestisce ...
* Apache Kafka
analizzare flussi di eventi


* Capitolato
**Documento** in cui il proponente

CSS: esempio i siti web e  **le relative pagine **.

* dApp
dApp sta per Applicazioni distribuite, ossia applicazioni che **operano su un** sistema informatico distribuito.

?Docker

* Gulpease
**valore 100 indica ** la
leggibilità più alta **e 0 la ** leggibilità


* Google Drive
togliere "online" alla fine

* GraphQL
GraphQL è un linguaggio di query **per API** e **un** runtime lato server ...

togliere ",di fatto ,"



* Java
modificherei così:
Java è un linguaggio di programmazione ad alto livello, orientato agli oggetti e a tipizzazione
statica. 
**Si appoggia sulla Java Virtual Machine per l'esecuzione e questo lo rende indipendente dalla piattaforma hardware sottostante.**


* Kotlin
multi-paradigma **ed** open source

**Comment by ivanpak** [comment]
@ToldoDM @antobaddo
