### ISSUE TITLE
[VER] Stesura verbale 2021-02-11

### ISSUE THREAD

**Issue by matteobudai** [DPCMGroup/dpcm2077-docs#69]
Stesura verbale del 2021-02-11.

Redattore: @matteobudai 
Verificatore: @samudg7 
Approvatore: @ivan-piacere

**Comment by samudg7** [comment]
Verifica

Motivazione scelta utilizzo pull request:  Da aggiungere:
per controllare al meglio ciò che può entrare o meno nella repo, ed eventualmente segnalare in modo mirato eventuali modifiche da apportare.

Idee prof of concept: Da aggiungere:
In particolare, si è pensato di rappresentare uno o più casi d'uso relativi all'amministratore e la sua interazione con il sistema e la blockchain.
